name: Deploy Preview

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Minify files
        uses: nizarmah/auto-minify@v3
        with:
          directory: '.'
          overwrite: true

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GH_PAGES_TOKEN }}  # Use the PAT secret
          branch: gh-pages-preview-${{ github.head_ref }}
          folder: .
